name: expense_tracker
description: "A feature-rich expense tracking app with a modern UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  fl_chart: ^0.68.0  # Stable version compatible with Flutter 3.32.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

